### ISSUE TITLE
入力だけでなく出力の自動生成もしたい

### ISSUE THREAD

**Issue by kmyk** [kyuridenamida/atcoder-tools#104]
例えば以下のようなコードが生成できるようになってほしいです。
出力部分を書かなくていいのは単に楽ですし、これができれば自動でサンプルをテストする機能を生成コードの中に組み込めたりもしてうれしいです。

``` c++
bool solve(int n) {
    ...
    return answer;
}

int main() {
    ...
    bool answer = solve(n);
    cout << (answer ? "Yes" : "No") << endl;
}
```

**Comment by kyuridenamida** [comment]
出力は割とフォーマットの解析が難しいという話があるんですが、yes / no questionにおいて単一出力っぽいことを検出する程度とかなら出来る気がしますね。

**Comment by fukatani** [comment]
整数一個だけ返せばいいやつとかもなんとかなりそうですか。

**Comment by kmyk** [comment]
簡単に眺めてみたところ、値をひとつだけのやつが7割くらい、残る2割も複雑なやつは自然言語でなくて `<pre>` で示してくれてるのでできそうです。出力が複雑な場合はそのようなケースがちゃんとサンプルに含まれるので安心してよさそう。AtCoderは優秀。

**Comment by kmyk** [comment]
整理:

-   値をひとつだけ答えるやつ
    -    真偽値 (`yes` / `no`)
    -    整数
    -    文字列
    -    浮動小数点数
-   もし存在すれば ~ 系
    -    存在すればその文字列を、存在しなければ `-1` を
    -    存在すれば `possible` に続けてその構成されたものを、存在しなければ `impossible` を
-    多値
    -    値 x y をこの順に出力せよ
    -    値 f(2), f(3), ... f(k) を出力せよ
    -    グラフ
-    クエリ系
    -   それぞれのクエリについて、...

**Comment by fukatani** [comment]
ほー、流石です。

https://atcoder.jp/contests/abc111/tasks/arc103_b
↑これとかはむりですよね？

**Comment by kmyk** [comment]
やればできると思います。
入力の解析と同様に `<pre>` の中を読んで形状を把握し、サンプルと見比べて型を判断すればよいです。

**Comment by kyuridenamida** [comment]
特にこのへんに着手する予定が直近にないので一旦wontfixで閉じます。

皆様ありがとうございました。

需要があったらもう一度開くか新しいissueを作ることで対処したいです
