### ISSUE TITLE
解析結果の一覧ページのAPI化とコード自動生成機能のuserscript化

### ISSUE THREAD

**Issue by kmyk** [kyuridenamida/atcoder-tools#105]
https://kyuridenamida.github.io/atcoder-tools/#/quality/summary のページには全問題の解析結果が含まれていることに気付きました。これの内部に含まれているデータをもうすこし扱いやすい形式で (たとえば `https://kyuridenamida.github.io/atcoder-tools/api.json` のようなURLを叩くだけなど) で提供してほしいです。
用途は、userscriptからatcoder-toolsを使えるようにすることです。

**Comment by kyuridenamida** [comment]
わかりました。全データダウンロードするのパフォーマンス大丈夫ですかね(あとキャッシュによる不具合とか)

**Comment by kmyk** [comment]
丸ごとひとつの json の形で大丈夫です。
ただし https://kyuridenamida.github.io/atcoder-tools/manifest.json とほぼ同様に設置されると仮定しています。

1回の通信の容量はいまそのまま解析結果のページを開くのと同じ量なので 300KB と大きくなく 200ms と十分に高速、接続数が増えたとしてもAtCoder のユーザ数程度なら GitHub pages は耐えてくれます。キャッシュも適切に設定されているので、複数ページを開いても重複しての通信はないので安心です。
また、もし最適ではなかったとしても、 userscript の内部で使うAPIなので互換性は気にせず壊すことができるので、問題が起こってから考えても遅くはないです。

**Comment by kyuridenamida** [comment]
OKです。ダウンロード出来るようにしてみます。

**Comment by kmyk** [comment]
よろしくお願いします。

**Comment by kyuridenamida** [comment]
https://kyuridenamida.github.io/atcoder-tools/api/all.json
これでいいですか?型はQualityResult.tsの定義を見てください

```
import Problem from './Problem'

export default interface QualityResult {
    problem: Problem,
    contest: {
        contest_id: string,
    },
    statement_parse: {
        error: string | null
    },
    format_prediction: {
        error: string | null
    },
    modulo: {
        value: number | null
        error: string | null
    },
    yes_str: {
        error: string | null
        value: string | null
    },
    no_str: {
        error: string | null
        value: string | null
    },
    codes: {
        [lang: string] : string,
    }
}
```

**Comment by kmyk** [comment]
完璧です。
ではuserscriptを書きます

**Comment by kyuridenamida** [comment]
いい話
