### ISSUE TITLE
デフォルトのテンプレートに宣伝を入れたい

### ISSUE THREAD

**Issue by kmyk** [kyuridenamida/atcoder-tools#113]
宣伝は重要であり、入れておいた方が得をすると予想できるからです。
1行目や `{{input_part}}` の上などに以下のような文章を追加する想定です。

``` c++
// This code is generated by atcoder-tools v1.1.12 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line with customizing your template)
#include <bits/stdc++.h>
using namespace std;
...
```

評価としては以下のようになり、メリットの方が多いと考えてます。

メリット:
-   存在が直接の利用者以外にも認識される
-   (副次的に) テンプレートをカスタマイズすることへの誘導になる
-   (追加するのは簡単)

デメリット:
-   ちょっと不快感がある

---

メリットに挙げた宣伝効果について:
ユーザ、特に「操作を自動化したい」みたいな発想を持たないパソコン苦手勢にこの手のツールの存在を伝えるには積極的な布教が必要です。「サンプルテストの自動化」「入力部分のコード生成」の概念を持っていないような人は多いので「最近なんか提出コードに名前が書いてある atcoder-tools ってなんだろう」という方向から入口を用意するのは妥当であるはずです。
ユーザが増えることに意味があるのかどうかについてですが、便利ツールは使われて初めて価値になりますし、この手のパソコン系のテクを普及させるのは競プロ界隈にとって有益のはずです。

デメリットとしての不快感について:
「生成コードに常に挿入されて設定ファイル等では外せない」とかならかなり不快感が強いですが、デフォルトのものに入っているだけなら許容範囲だと思います。

**Comment by kyuridenamida** [comment]
メリットとデメリット、不快感に関する考察も含めて実は全く同じことを考えてました(でも自分の感覚に確証が持てなかったため保留していた)。これは同意です。

>「生成コードに常に挿入されて設定ファイル等では外せない」とかならかなり不快感が強いですが、デフォルトのものに入っているだけなら許容範囲だと思います。

↑わかります。むしろカスタムテンプレートの設定を学びたくなる人が増えていいかもしれない(放言です)
