### ISSUE TITLE
エラー出力の削除要求の有無を設定可能にする

### ISSUE THREAD

**Issue by blue-jam** [kyuridenamida/atcoder-tools#119]
AOJとは違い、AtCoderではstderrに何かを出力をしてもランタイムエラーにならない。（コンテスト個別の設定によってエラーになるかは知らない）

現状では`atcoder-tools test`でテストを行った際、デバッグ用にエラー出力を出しただけでテストが失敗し不便である。少なくとも、エラー出力を無視するように設定できるべき。

**Comment by kyuridenamida** [comment]
元々導入した理由が、エラー出力があるとデバッグ出力に余分な計算量かけてるケースでTLEを食らうというシチュエーションの回避だったんですが、実際エラー出力取り除くのってどれくらい手間なんですかね。

需要があるならオプションを導入するのは賛成で、ただし個人的にデフォルトは余分なエラー出力をしているプログラムを不正解として扱うようにしたいです。どうでしょうか。

**Comment by blue-jam** [comment]
> エラー出力を取り除くのってどれぐらい手間なんですかね

提出前にエラー出力を省くのが手間かどうかという問題ではなく、ユースケースを考えたときにユーザにどれだけ負荷がかかるかという問題だと思っています。エラー出力に何か出力しているとき、ユーザはプログラムを修正しながらテストを何回も走らせているはずで、その際にいちいちエラー出力の削除をしないとテスト結果を確認できないというのはユーザにとって余計な負担だと思います。

例えば、私はテストでWAが出ると

1. エラー出力に計算途中の値や探索の状態を出力する
2. 出力された値が本来あるべき値と異なっていれば、プログラム中に間違いがあるはずなので探して修正する
3. 再びテストを走らせてエラー出力の値とWAが修正されたか確認する。修正されていなければ、1か2に戻って修正を繰り返す

という手順でプログラムを修正します。

このような使い方をしているときに、エラー出力に何かを出しているだけでテストに失敗したと判定されてしまうと、手順3でWAが修正されたかどうかを確認するのが難しくなります。

一応、エラー出力がある場合には"CORRECT but with ..."とテストケースごとに出力されていますが、テスト結果のサマリーには失敗としてカウントされています。そのため、テスト結果を実行するたびに、コンソールをスクロールしてテストケースごとの結果を目視で確認することになっていて、手間がかかると同時に、確認ミスのリスクが生じています。

> 個人的にデフォルトは余分なエラー出力をしているプログラムを不正解として扱うようにしたいです。どうでしょうか。

前述のような使い方をしていることもあり、私は標準出力が間違っていることと、エラー出力があることは分けて考えるべきだと思っています。私であれば、

1. パスしたテストケースの個数とは別に、エラー出力があったかどうかのフラグを用意する
2. エラー出力があれば、テストケースの通過率とは別にエラー出力の削除を提案する旨を出力する

という実装にします。エラー出力があったときに提出をブロックするべきかどうかについては、私はオープンです。
