### ISSUE TITLE
codecov.io との連携を見直した方がよい気がする

### ISSUE THREAD

**Issue by kmyk** [kyuridenamida/atcoder-tools#135]
現状はcommitの横に ❌ のマークを表示するためだけのものになっているように見えます。
coverageの計測は無駄ではないですが、現状では「品質管理がだめそうなプロジェクト」という印象を与える不利益の方が大きそうです。
設定の修正や連携解除を検討してみてほしいです。

**Comment by kyuridenamida** [comment]
やっておきました。特にpatchは0にしました。
https://github.com/kyuridenamida/atcoder-tools/commit/48880c98c3beb272bbbfbbbbb6a36dbe043f2162

**Comment by kmyk** [comment]
よさそう
