### ISSUE TITLE
小数ジャッジの時に1e-9みたいな指数表記の出力を弾く

### ISSUE THREAD

**Issue by kyuridenamida** [kyuridenamida/atcoder-tools#163]
小数ジャッジの時に1e-9みたいな指数表記の出力を弾く。現状pythonのfloat("1e-9")とかは正しくキャストが行われてしまう。atcoderがAC判定するならいいんですけどどうなんだっけ

**Comment by chaemon** [comment]
これとは違う問題かもしれませんが、内部的にはfloatが10進法でなく2進法で扱われていることによる謝ったジャッジがありそうです。例えば、誤差が0.001まで許容で答えが5のときに、5.001と答えたら、通常はACのはずですが、abs(5.001-5) <= 0.001の判定を二進法のfloatで行っていたら、もしかしたらWAになっちゃわないかと思っています。

**Comment by kyuridenamida** [comment]
@chaemon 
まあいいんじゃないですかねそれくらい(誤差ギリギリの答えを出力せざるを得ないケースって思いつかない...

**Comment by kyuridenamida** [comment]
1年以上開いてるかつ優先度が低いのでwontfixとして閉じます。
