### ISSUE TITLE
[Feature Request] AtCoder のユーザー名, パスワードを環境変数で渡す

### ISSUE THREAD

**Issue by sei40kr** [kyuridenamida/atcoder-tools#169]
環境変数で AtCoder のログイン情報を渡せるようにしたい。

(そうすることによって Emacs から提出できるようにしたい)

**Comment by kyuridenamida** [comment]
こんにちは!  一度ログインすると`/home/{user名}/.local/share/atcoder-tools/cookies.txt`に認証情報が登録されて、以降入力が省略できますが、それを頼るのは選択肢にないですか?
現状標準入力を強制している部分をもしパスワードとユーザー名が環境変数にあれば渡す、という風に変えることはできますが、セキュリティ上の問題からあまりユーザーに生パスワードを環境変数に入力するのを推奨したくないという立場です。

**Comment by sei40kr** [comment]
`~/.local/share/atcoder-tools/cookies.txt` はまだ見てませんでした :bowing_man: 
一旦 close します。
