### ISSUE TITLE
文字列判定のロジックを追加

### ISSUE THREAD

**Issue by chaemon** [kyuridenamida/atcoder-tools#170]
https://atcoder.jp/contests/abc146/tasks/abc146_f

こちらの問題において、Sが整数と誤判断されてしまう事象が発生しました。対策として、01001010みたいに0から始まる文字列は整数とは判断せず文字列とする、長さが20以上のもの(64bitに収まらない)も文字列とするなどがあると思います。

問題文を読むとかもっと高度な対策をするなら、S[]のように[]演算子で呼ぶ記述があるなら文字列とかも考えられるんじゃないかなーと思います。逆に、S<Tみたいに比較してたら整数・・・かとも思ったのですが文字列の辞書順とかもあるので、一概には言えないですね。

**Comment by kyuridenamida** [comment]
判定精度を上げるためのメタ情報を抽出して、それらを総合的に加味して…みたいな形で柔軟に対処することはできそうですがひとまずは最も人が入出力欄だけを見て明らかだと思うケースだけサポートするのが良いかと思います。0はじまりで長さが2以上もしくは長さが20以上なら…というのも同意です。
