### ISSUE TITLE
genコマンドでの生成時に既存ファイルを上書きする件について

### ISSUE THREAD

**Issue by Y-Kuro-u** [kyuridenamida/atcoder-tools#171]
表題の通りgenコマンドでファイルを生成する際に同名ファイルを上書きするのを防ぎたいです。

**Comment by Y-Kuro-u** [comment]
すみません、main.cppを想定しています。

**Comment by kyuridenamida** [comment]
現状main.cpp.1とかのファイルが生成されてそっちに保存されると思いますが、それだと駄目ですか？

**Comment by Y-Kuro-u** [comment]
すみません、完全に見落としていました。
単純にmain.cppのみを確認してしまっていたため前回までのファイルが消えたと勘違いしていました。
