### ISSUE TITLE
atcoderサイト変更対応

### ISSUE THREAD

**Issue by gghatano** [kyuridenamida/atcoder-tools#198]
2020年5月14日？から、atcoder-tools gen すると、
ログインは成功するのに問題がパースされませんでした

atcoderのサイトに変更があったらしく、selectorを変更したら手元では正しく動きました。
https://github.com/kyuridenamida/atcoder-tools/pull/197

**Comment by kyuridenamida** [comment]
報告ありがとうございます。1.1.7にて修正されたと思います。
