### ISSUE TITLE
Universal code generatorのテンプレートを指定したい

### ISSUE THREAD

**Issue by firewood** [kyuridenamida/atcoder-tools#232]
Universal code generatorで使うTOMLファイルをカスタマイズしたいときに(たぶん)開発版をインストールする必要がありますが、設定ファイルまたはコマンドラインオプションで指定できるとよいと思います。
また `code_generator_file` オプションは役割を終えたので消してもいいのではないでしょうか。

**Comment by chaemon** [comment]
こちらで言語ごとにconfigが指定できるようにしますので、これが完了してマージされたら、言語ごとにTOMLファイルを指定とかもできるようになると思います。

https://github.com/kyuridenamida/atcoder-tools/pull/233

**Comment by chaemon** [comment]
code_generator_fileはUniversal code generatorでカバーできない言語が出てきたときとかに指定したくなるかもしれないですね。

**Comment by chaemon** [comment]
本機能をこちらで実装しました。

https://github.com/kyuridenamida/atcoder-tools/pull/237

**Comment by kyuridenamida** [comment]
リリース大変遅くなりました。#237がマージされたのでこのissueはcloseします。

> また code_generator_file オプションは役割を終えたので消してもいいのではないでしょうか。

役割を終えたかというと言い過ぎで、一応下位互換性と対処できないケースのために残しておきます。
