### ISSUE TITLE
入力フォーマットの中間形式の仕様策定

### ISSUE THREAD

**Issue by kyuridenamida** [kyuridenamida/atcoder-tools#39]
入力フォーマットのより良い中間形式について議論する
+@asi1024

**Comment by kmyk** [comment]
> * 区切り文字情報を持たせるべきかどうか

Python のような言語があるので改行情報は必要です

**Comment by susurri** [comment]
Ruby で
```
N K
S
```
を一行ずつ読んで
```
N, K = gets.split.map(&:to_i)
```
にしたかったのですが、`[(Singular: N),(Singular: K),(Singular: S)]` になってしまうので
諦めました。N, K は空白区切りで一行に入っている、というような情報があると良いです。

**Comment by kyuridenamida** [comment]
特にこのへんに着手する予定が直近にないので一旦wontfixで閉じます。

皆様ありがとうございました。

需要があったらもう一度開くか新しいissueを作ることで対処したいです
