### ISSUE TITLE
おい！！！！！！！！！！！！！！！！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by yosupo06** [kyuridenamida/atcoder-tools#7]
kupc2016で死んだ

ウ　ン　チ　ー　コ　ン　グ

**Comment by asi1024** [comment]
H問題の入出力の部分を少し修正しました．正しくサンプル入出力を取得できるようになったはずです．

**Comment by kyuridenamida** [comment]
KUPC2016 H問題のフォーマットがいつもと違うため読み込めなかったようです。
@asi1024 
そちら側が対応してくれるとは思っていませんでした。ありがとうございます。
リアクティブの対応は限界があるので対応の予定はありません。
