### ISSUE TITLE
ランダムケース自動で作りたい…作りたくない？

### ISSUE THREAD

**Issue by aki33524** [kyuridenamida/atcoder-tools#8]

**Comment by kyuridenamida** [comment]
ランダムテストケース生成は現状やる予定がないです。

将来のコントリビューションは拒否する意図はありませんが以下のツールがケース自動生成も責務に含めておりかつより新しいのでそちらにコントリビューションするのが良いかと思われます。

https://github.com/online-judge-tools/template-generator
