### ISSUE TITLE
REのとき、何か途中まで出力されても捨てられる

### ISSUE THREAD

**Issue by tokoharu** [kyuridenamida/atcoder-tools#83]
表題の通りで、Segmentation Faultなどをするときに[RE]のみが出てしまいます。print debugをatcoder-tools上でやりたい時もあると思うので、サポートしてくれると嬉しいです。

**Comment by kyuridenamida** [comment]
feature branchにpush -fしたら変な感じになったんですが2個目のコードが正しいです。
PRつくります。

![image](https://user-images.githubusercontent.com/233559/52001165-1c82b080-2502-11e9-822c-7d6928c35ad6.png)

**Comment by kyuridenamida** [comment]
#84 PR 確認よろです　@tokoharu

**Comment by kyuridenamida** [comment]
`sudo pip3 install git+git://github.com/kyuridenamida/atcoder-tools.git@issue/83  --upgrade`
お試しコマンド情報です
