### ISSUE TITLE
readmeのDemoが消えてる

### ISSUE THREAD

**Issue by kmyk** [kyuridenamida/atcoder-tools#85]
`This recording has been archived` になってます。
対応としては軽めのgifにしてGitHubのIssuesやWikiにuploadするのがおすすめです。

**Comment by kyuridenamida** [comment]
ありがとうございます。今見たらなんかデカデカとダサいスクショにすり替わっており、かなりショックを受けています(参考にします!)

**Comment by kyuridenamida** [comment]
@kmyk ところで最近適当なツールでトライしたらクソデカgifができて苦しかった(圧縮しても2MBとか)んですが、kimiyukiさん自身はどういうツールを使って撮影したか教えてくれたりしませんか?参考にしたいです

**Comment by kmyk** [comment]
たしか ttyrec というのを使ったはずです。
端末に文字が描画された結果を録画するのでなく、端末に出力される文字情報を記録してそこからgifを復元するので軽くなります。

今思い返せば圧縮はも gifsicle というコマンドを使ってframeを手動で間引くなどの非自明な操作をしていた気がします。もしかすると安易に勧めるべき手法ではなかったかもしれません。

**Comment by kyuridenamida** [comment]
悪戦苦闘の末、`asciinema` + `asciicast2gif` という解決策に落ち着きました。asciicast2gifがgifsicleを内部で使っていて、いい感じに出力してくれました。リサイズが必要だったので再度gifsicleを使いましたが...なかなかいい感じでした

![out5](https://user-images.githubusercontent.com/233559/52807100-f6e2d300-30cd-11e9-8906-82b9f9b2dff7.gif)

**Comment by kyuridenamida** [comment]
ttyrecはなんか手元でvimと一緒に動いてくれたので諦めてしまいましたが、なんとかなりました。@kimiyukiさんありがとうございました。

**Comment by kyuridenamida** [comment]
アップロードして満足してたけど冷静に考えてreadmeなおしてないな
