### ISSUE TITLE
コード自動生成機能だけ利用できるコマンドがほしい

### ISSUE THREAD

**Issue by kmyk** [kyuridenamida/atcoder-tools#96]
現状はコード自動生成機能は `atcoder-tools gen CONTEST_ID` のサブコマンドを用いて間接的にしか利用できません。これは「単独の問題ごとの利用ができない」「ディレクトリ構造が固定される」などの不都合があります。なので、単体でこの機能を使えるサブコマンドがほしいです。

具体的なインターフェースの形としては `atcoder-tools codegen [-l LANGUAGE] URL > PATH` か `atcoder-tools codegen URL PATH` (言語は `PATH` から判別) などが使いやすいかなと思います。
対象の指定方法は url であるべきのはずです。task_id だけの指定では contest_id の復元が不可能であり、contest_id と task_id をふたつ指定するのは url コピペするだけに比べて煩雑なためです。
出力先は特定のディレクトリ構造に依存するべきでないので (そういう趣旨でのコマンドの追加なので)、標準出力を使うか引数として受けとるべきです。

**Comment by kmyk** [comment]
(atcoder-tools 単独で閉じていない話があったので先にTwitter ( https://twitter.com/a3VtYQo/status/1096099813441949697 ) 上で話を持ち掛けていますが、それとは独立にこちらにもサブコマンドを追加したいです。もし機能を別プログラムに切り出すとしても atcoder-tools の内部での切り出しが先のはずなので)

**Comment by kmyk** [comment]
インターフェースの形がよさそうなら書いてプルリクを投げる予定です

**Comment by kyuridenamida** [comment]
確かに入出力ダウンロードはおまけでしたがコマンド一つでコンテストを始めれることを思想にしてたので、コマンドレベルでの分離を全く想定してませんでした。
コードレベルではある程度独立しているのでatcoder toolsをpythonライブラリとして使う分には再利用は可能だと思います。ただ、一つ懸念があって問題文のパース結果を入力としてpredictorに与えてるのでそこが少し使いにくいかもしれません

**Comment by kyuridenamida** [comment]
APIはそれでokです。
標準出力を使うのがいい気がしますね。

**Comment by kmyk** [comment]
了解です。ではそのような感じでやってみます

**Comment by kyuridenamida** [comment]
template, code generatorのpathもオプショナルで引数指定できるようにしておいていただけると助かります。

この場合codegeneratorが指定された場合は多分langの指定が必須じゃなくなるはずです。
こういう場合の解決策をよく知らないのですが、
--codegenerator filepathではなく --codegenerator cppとかいう特殊なパターンを許してlangとの整合性の問題をなくすというのはどうでしょう。

**Comment by kmyk** [comment]
複雑な依存関係のオプションは、すべてオプショナル引数として受けとってから自分で解析をして必要なら `ArgumentParser.error` をすると実現できます。
